# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Iac(_OnPrem):
    _type = "iac"
    _icon_dir = "resources/onprem/iac"


class Ansible(_Iac):
    _icon = "ansible.png"


class Awx(_Iac):
    _icon = "awx.png"


class F5Applicationservices3(_Iac):
    _icon = "f5applicationservices3.png"


class F5Declarativeonboarding(_Iac):
    _icon = "f5declarativeonboarding.png"


class Terraform(_Iac):
    _icon = "terraform.png"


# Aliases
